image: python:3.11-bullseye

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install .

stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - pip install h5py
    - python -m unittest discover tests --verbose

pages:
  stage: deploy
  script:
    - pwd
    - ls -lht
    - apt-get -yq update
    - apt-get -yq install pandoc
    - pip install ./
    - pip install ipython
    - pip install sphinx sphinx-rtd-theme nbsphinx parso pandoc>=2.11
    - cd docs ; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - main
    
