image:
  name: openjournals/inara
  entrypoint: ["/bin/sh", "-c"]

stages:
  - deploy

paper:
  stage: deploy
  variables:
    GIT_SHA: $CI_COMMIT_SHA
    JOURNAL: joss
  script:
    - inara -o pdf,cff JOSSpaper/paper.md
  allow_failure: false
  artifacts:
    paths:
      - JOSSpaper/paper.pdf
      - JOSSpaper/CITATION.cff
  needs: []