image:
  name: openjournals/inara
  entrypoint: ["/bin/sh", "-c"]

stages:
  - deploy

paper:
  stage: deploy
  variables:
    GIT_SHA: $CI_COMMIT_SHA
    JOURNAL: jose
  script:
    - inara -o pdf,cff JOSEpaper/paper.md
  allow_failure: false
  artifacts:
    paths:
      - JOSEpaper/paper.pdf
      - JOSEpaper/CITATION.cff
  needs: []